### ISSUE TITLE
Orthofinder fails when using RAxML

### ISSUE THREAD

**Issue by jlanga** [davidemms/OrthoFinder#93] opened 2017-07-06 14:11 UTC
Command call:
```sh
orthofinder \
     --from-groups sequences/ \
     --only-alignments \
     --method msa \
     --algthreads 24 \
     --msa_program mafft \
     --tree_program raxml
```
Output:
```
OrthoFinder version 1.1.8 Copyright (C) 2014 David Emms

    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.
    For details please see the License.md that came with this software.

16 thread(s) for highly parallel tasks (BLAST searches etc.)
24 thread(s) for OrthoFinder algorithm

Using orthogroups in file:
    /root/sequences/Orthogroups.txt
and corresponding clusters file:
    /root/sequences/clusters_OrthoFinder_v1.1.8_I1.5.txt_id_pairs.txt

Checking required programs are installed
----------------------------------------
Test can run "fastme -i /root/sequences/SimpleTest.phy -o /root/sequences/SimpleTest.tre" - ok
Test can run "mafft /root/sequences//_dependencies_check/SimpleTest.fa" - ok

RAxML can't, parse the alignment file as phylip file 
it will now try to parse it as FASTA file

RAxML output files with the run ID <test> already exist 
in directory /root/ ...... exiting
ERROR: Cannot run user-configured tree method 'raxml'
Please check program is installed and that it is correctly configured in the ~/.orthofinder.config file

Dependencies have been met for inference of orthogroups but not for the subsequent orthologue inference.
Either install the required dependencies or use the option '-og' to stop the analysis after the inference of orthogroups.

ERROR: An error occurred, please review previous error messages for more information.
```

When running raxml on its own with the test fasta,

```sh
 raxmlHPC-AVX \
    -m PROTGAMMALG \
    -p 12345 \
    -s sequences/_dependencies_check/SimpleTest.fa \
    -n test
```
the output is the following:
```

RAxML can't, parse the alignment file as phylip file 
it will now try to parse it as FASTA file

TOO FEW SPECIES

```

Please add more test species or delete the check.

**Comment by davidemms** [comment] 2017-07-14 16:23
Hi Jorge

Thanks for letting me know about this. The problem is in OrthoFinder's configuration file telling it how to run RAxML. I'll submit a fix for this.

In the meantime, you can make a change to the configuration file on your machine to get it working. You'd need to edit the config.json file found in the same directory as the orthofinder.py script. The entry for RAxML should look like this:

>     "raxml":{ 
>     "program_type": "tree",
>     "cmd_line": "raxmlHPC-AVX -m PROTGAMMALG -p 12345 -s INPUT -n IDENTIFIER -w PATH > /dev/null",
>     "ouput_filename": "PATH/RAxML_bestTree.IDENTIFIER"
>     },

Note that I've included "> /dev/null" in the command line. This prevents it printing loads of output to screen when inferring gene trees for all the orthogroups but you can remove this part if you need to debug anything and then the output will be printed to screen.

The SimpleTest.fa file that you found is not actually the one used to test RAxML, the test file actually used does in fact have enough sequences in it and with RAxML configured correctly the test passes fine.

All the best
David

**Comment by jlanga** [comment] 2017-07-18 10:21
Thanks!

**Comment by davidemms** [comment] 2017-07-20 14:05
Resolved in https://github.com/davidemms/OrthoFinder/commit/044dc91e400690b445c9736260f23b1c11285f5a

**Closed by davidemms** 2017-07-20 14:05 UTC
