### ISSUE TITLE
Problem with diamond on mac (orthofinder v2.3.8)

### ISSUE THREAD

**Issue by LovellHAGSC** [davidemms/OrthoFinder#328] opened 2020-01-06 19:01 UTC
Hi there, 
I recently updated to orthofinder v2.3.8 on my Mac (running Mohave 10.14.3) via conda. 
Now, when I run default orthofinder on the test data, I get an error related to finding the diamond executable. If I downgrade to orthofinder v.2.3.3 from conda I do not get this error. 
Diamond is definitely in the path and installed as a dependency through conda. 

Furthermore, if I run -S blast, orthofinder v2.3.8 can't find mcl. Errors are printed below. 

Any advice on how to run v2.3.8 on a mac is much appreciated. 
John

#################
`conda install -c bioconda orthofinder`
`orthofinder -f path/to/OrthoFinder_source/ExampleData/`

Checking required programs are installed
----------------------------------------
ERROR: Cannot run diamond
Format of make database command:
  diamond makedb --in INPUT -d OUTPUT

#################
`orthofinder -f path/to/OrthoFinder_source/ExampleData/ -S blast`

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - failed

**Comment by LovellHAGSC** [comment] 2020-01-07 02:55
I am now seeing https://github.com/davidemms/OrthoFinder/issues/318. Let me know if you figure out the conda recipe. 
John

**Comment by davidemms** [comment] 2020-01-09 17:24
Hi John

Are you able to run diamond and mcl from the bioconda install? If not, are you able to report that problem (or fix it if you have the know-how)> 

Or do they run ok and then the problem occurs when OrthoFinder tries to run them? Unfortunately it is very difficult for me to investigate such problems as I don't have access to a mac to investigate these things on and, to make it worse, it only seems to be a problem on some macs so it's unclear where the error is coming from. 

If mcl runs but OrthoFinder can't run it then let me know.

Many thanks
David:

**Comment by LovellHAGSC** [comment] 2020-01-09 17:51
Hi David, thanks for your quick response. 
Yes, MCL and diamond run no prob when called outside of orthofinder. I can send the full code / output if you'd like. This issue only arose in the most recent orthofinder version. v2.3.7 (i think) worked fine. v2.3.3 (the latest non v2.3.8 version) works fine on conda. 
Cheers,
John

**Comment by LovellHAGSC** [comment] 2020-01-27 17:37
Have you made any progress figuring out the conda recipe?

**Comment by davidemms** [comment] 2020-01-29 14:26
Hi John

I'm looking into this to see if I can figure out what might be going wrong. 

OrthoFinder requires that mcl print to stdout if the command "mcl -h" is called and that nothing gets printed to stderr. The requirement on stderr could potentially be too stringent in some cases, so I could remove that check, this may help. 

However, that would explain the problem with diamond. For diamond, all that it requires is that if orthofinder gets it to create a database and do a search then it should get a results file. I can't think of what could go wrong here. Not with diamond working correctly anyway. I could provide an option to allow you to force orthofinder to skip all the checks and try and run anyway to see if that works, it might move us forward at least.

The full output from running each of the following commands would be good to see in case there's anything we're missing:

```
mcl -h
diamond makedb --in Species0.fa -d DBSpecies0
diamond blastp -d DBSpecies0 -q Species0.fa -o test_search_results.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1
orthofinder -f path/to/OrthoFinder_source/ExampleData/
```

As you can probably appreciate, it's very hard to debug without having a way of reproducing the issue myself. Thanks for your help on this.

David

**Comment by davidemms** [comment] 2020-01-31 15:19
So it looks like there may be an issue with latest versions of diamond, which hasn't been resolved yet. Conda will all you to install a version of diamond that doesn't exhibit this problem (i.e. v0.9.24):
`conda install -c bioconda diamond=0.9.24-0`

(see https://github.com/davidemms/OrthoFinder/issues/335)

If anyone is finding the latest version of diamond isn't working on their Mac because of an "illegal instruction" / error code -4 then I think Benjamin would appreciate any help you're able to give tracking it down:

https://github.com/bbuchfink/diamond/issues/303

All the best
David

**Comment by LovellHAGSC** [comment] 2020-01-31 19:44
Hi David, thanks for the help. As far as I can tell, the issue is bigger than the conda install. 
I have installed everything independently and placed MCL, fastme, diamond in the path. They run fine on their own, but I still get the error. I get this both from the executable and the python script. Calls to orthofinder and diamond below. Is it possible to specify the directories containing the various dependencies, instead of requiring they are in the path?
If not, its no prob to run on linux, but I'd like to be able to run on mac too. 
John

python ../OrthoFinder_source/orthofinder.py -f ExampleData 

OrthoFinder version 2.3.8 Copyright (C) 2014 David Emms

2020-01-31 12:24:42 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------

ERROR: Cannot run diamond


I can confirm that diamond runs fine and is in the path:

diamond makedb --in ExampleData/Mycoplasma_agalactiae.faa -d test
diamond v0.9.29.130 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: ExampleData/Mycoplasma_agalactiae.faa
Opening the database file...  [0.006582s]
Loading sequences...  [0.004205s]
Masking sequences...  [0.010604s]
Writing sequences...  [0.001237s]
Hashing sequences...  [0.000156s]
Loading sequences...  [1.2e-05s]
Writing trailer...  [5.6e-05s]
Closing the input file...  [3e-05s]
Closing the database file...  [0.000166s]
Database hash = a2028499010f57df0b6ff87dfe48bb78
Processed 820 sequences, 295442 letters.
Total time = 0.02316s

**Comment by davidemms** [comment] 2020-02-03 10:51
Hi John

Could you also confirm that the search command works too:
`diamond blastp -d test -q ExampleData/Mycoplasma_agalactiae.faa -o diamond_output.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1`

Thanks
David

**Comment by LovellHAGSC** [comment] 2020-02-03 20:02
Hi David, 
I can confirm that the diamond command works fine.  I can also confirm that the same issue exists in 2.3.7, but not 2.3.3. I'll email you the full output of my tests, so that we don't fill up this thread with junk. 
John

**Comment by LovellHAGSC** [comment] 2020-02-03 20:37
I'll point out that the temporary fix I have found:
1. install orthofinder v2.3.3 from conda
2. manually delete the diamond install that comes with the conda environment
3. install diamond manually and add to path

**Comment by davidemms** [comment] 2020-02-04 14:08
Hi John

I'm sorry, there may have been something simple I missed because I thought I'd said it on this issue but instead in must have been on another issue. Could you try deleting the 'bin' directory that's in the conda install of OrthoFinder. E.g, on my machine

```
$ which orthofinder 
/home/emms/miniconda3/bin/orthofinder
$ ls /home/emms/miniconda3/bin/scripts_of/bin/
diamond  fastme  mcl
$ rm -r /home/emms/miniconda3/bin/scripts_of/bin/
```

In fact, I think this probably needs deleting from the conda recipe, I'm just getting the hang of it.

All the best
David

**Comment by LovellHAGSC** [comment] 2020-02-04 17:48
woot! That did it. 

1. Manually install diamond outside of conda
2. install orthofinder from conda
3. delete the miniconda3/bin/scripts_of/bin directory
4. delete the miniconda3/bin/diamond directory
5. add manual install of diamond to path. 

Thanks for the help/patience.
John

**Comment by davidemms** [comment] 2020-02-06 10:11
Hi John

I've now updated the bioconda recipe for orthofinder so that it now asks for a diamond version no later than 0.9.24, which I think is where the problem might have been coming from. If you're able to test it, it'd be great to know if this now works out of the box for you?

Many thanks
David

**Comment by 14zac2** [comment] 2020-02-06 18:29
Hi all,

I'm on a macOS Catalina and was having the exact same issues as mentioned in this thread. "orthofinder -h" was working perfectly, but diamond and mcl were constantly calling errors when trying to run the ExampleData. Removing the miniconda3/bin/scripts_of/bin directory solved the issue and it seems to be working now, and I'm using diamond 0.9.30. Do you still recommend the downgrade?

Thanks,
Zoe

**Comment by davidemms** [comment] 2020-02-06 18:52
Hi Zoe

That's really useful to know. To be honest I've been working in the dark on this issue as it's not one I'm able to test myself and neither do I know what changes are going into each diamond release. If diamond 0.9.30 is working for you then I'd definitely recommend sticking with that. 

What would be most helpful would be to know whether something like 0.9.26 works on your computer or not. If it doesn't then that would start to suggest that the issue has now been resolved in the later release. It's not a great situation to be recommending that people use an older version, so if that's no longer necessary then it'd be good to be able to update the advice.

Many thanks
David

**Comment by 14zac2** [comment] 2020-02-06 19:24
Hi David,

I'll work on it, but I'm having a hard time finding where to get an older version of diamond. I've tried through both bioconda and docker but they seem to be giving me version unknown errors when specifying 0.9.26. I'll let you know if I get it to work!

Zoe

**Comment by 14zac2** [comment] 2020-02-06 20:06
Hi David,

At first I thought the diamond version wasn't an issue because OrthoFinder appeared to be running, but it turns out I just didn't look closely enough at the error messages - I was indeed getting the following error with diamond: ERROR: external program called by OrthoFinder returned an error code: -4.

I have now installed diamond 0.9.26 and the OrthoFinder appears to be running properly (my run is not done yet).

Cheers,
Zoe

**Comment by davidemms** [comment] 2020-02-11 11:55
There was a further issue that may have been in play here: https://github.com/davidemms/OrthoFinder/issues/341

This has now been resolved. There's now a new release of OrthoFinder, 2.3.11, which is also available with bioconda. If anyone still has the same issue using the new version then please let me know as that's generally the only way I can find out about Mac-specific issues myself.

Thank
David

**Closed by davidemms** 2020-02-11 11:55 UTC
