### ISSUE TITLE
different number of trees in Gene_Trees and Recon_Gene_Trees

### ISSUE THREAD

**Issue by timedreamer** [davidemms/OrthoFinder#289] opened 2019-10-03 17:16 UTC
Hi there,

 I run a comparison between two species using `orthofinder -a 4 -t 16 -M msa -A mafft -f orthoFinder_ath_osa`.

 In the end, I got **10722** orthogroups. In the `Gene_Trees` directory, I got **3660** trees which matches the number of non-single orthogroups. However, in the `Recon_Gene_Trees`, I got **1355** trees. Did I miss any files? If I want to show the tree, do I use the `Recon_Gene_Trees` output? 

 Thank you!
Ji

**Comment by davidemms** [comment] 2019-10-04 13:09
Hi Ji

I'm sorry but I don't know why you got fewer trees in your Recon_Gene_Trees directory, that is not expected behaviour. Were the any messages in the output OrthoFinder printed? How many genes are there in the last (and therefore smallest) orthogroup in the Gene_Trees directory, and in the Recon_Gene_Trees directory? 

If you want to show the tree then in most cases I would use the one in the Gene_Trees directory. This is the gene tree direct from the tree inference software whereas the Recon_Gene_Trees directory shows how OrthoFinder interpreted the trees in order to deduce orthologs. Make sure you root the tree in Gene_Trees directory first though, you can look at how OrthoFinder rooted it in the Recon_Gene_Trees directory if that is helpful to you.

All the best
David

**Comment by timedreamer** [comment] 2019-10-04 14:30
Hi David,

 Thank you for the quick response. There are **3** genes in the last orthgroup in `Gene_Trees` directory. There are **4** genes in last group in `Recon_Gene_Trees`.

  I didn't save the screen output from my run, so I repeated again with using `diamond`: `orthofinder -S diamond -a 4 -t 4 -M msa -A mafft  -f oth`. I got a similar result (less Trees in `Recon_Gene_Trees`). Below is the screen output. Just one tiny suggestion if it's not already there, maybe write the run log to a file, in addition to the screen output. 

 It seems from the log, *Reconciling gene trees and species tree* only did for 1325 trees. Any ideas?

 Thanks!
Ji

---
log output:

```

OrthoFinder version 2.2.6 Copyright (C) 2014 David Emms

4 thread(s) for highly parallel tasks (BLAST searches etc.)
4 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "mafft /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth//_dependencies_check/SimpleTest.fa" - ok
Test can run "FastTree /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth//_dependencies_check/SimpleTest.fa" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2019-10-02 22:16:12 : Creating diamond database 1 of 2
2019-10-02 22:16:12 : Creating diamond database 2 of 2

Running diamond all-versus-all
------------------------------
Using 4 thread(s)
2019-10-02 22:16:12 : This may take some time....
2019-10-02 22:16:12 : Done 0 of 4

Running OrthoFinder algorithm
-----------------------------
2019-10-03 03:22:11 : Initial processing of each species
2019-10-03 03:22:29 : Initial processing of species 0 complete
2019-10-03 03:22:45 : Initial processing of species 1 complete
2019-10-03 03:22:51 : Connected putatitive homologs
2019-10-03 03:23:20 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthogroups.csv
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthogroups.txt (OrthoMCL format)
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthogroups_UnassignedGenes.csv
2019-10-03 03:23:23 : Done orthogroups

Analysing Orthogroups
=====================
2019-10-03 03:23:23 : Starting MSA/Trees

Inferring multiple sequence alignments and gene trees
-----------------------------------------------------
2019-10-03 03:31:13 : Done 5000 of 10838
2019-10-03 03:31:48 : Done 6000 of 10838
2019-10-03 03:29:55 : Done 3000 of 10838
2019-10-03 03:32:23 : Done 7000 of 10838
2019-10-03 03:25:20 : Done 0 of 10838
2019-10-03 03:28:14 : Done 1000 of 10838
2019-10-03 03:32:58 : Done 8000 of 10838
2019-10-03 03:33:33 : Done 9000 of 10838
2019-10-03 03:29:07 : Done 2000 of 10838
2019-10-03 03:30:38 : Done 4000 of 10838
2019-10-03 03:34:08 : Done 10000 of 10838
2019-10-03 03:22:54 : Written final scores for species 0 to graph file
2019-10-03 03:22:56 : Written final scores for species 1 to graph file
2019-10-03 03:35:00 : Done MSA/Trees

Reconciling gene trees and species tree
---------------------------------------
2019-10-03 03:35:00 : Starting Recon and orthologues
2019-10-03 03:35:00 : Starting OF Orthologues
2019-10-03 03:35:00 : Done 0 of 1325
2019-10-03 03:35:01 : Done 100 of 1325
2019-10-03 03:35:01 : Done 200 of 1325
2019-10-03 03:35:02 : Done 300 of 1325
2019-10-03 03:35:02 : Done 400 of 1325
2019-10-03 03:35:03 : Done 500 of 1325
2019-10-03 03:35:03 : Done 600 of 1325
2019-10-03 03:35:03 : Done 700 of 1325
2019-10-03 03:35:04 : Done 800 of 1325
2019-10-03 03:35:04 : Done 900 of 1325
2019-10-03 03:35:05 : Done 1000 of 1325
2019-10-03 03:35:05 : Done 1100 of 1325
2019-10-03 03:35:05 : Done 1200 of 1325
2019-10-03 03:35:06 : Done 1300 of 1325
2019-10-03 03:35:06 : Done OF Orthologues
2019-10-03 03:35:06 : Done Recon

Writing results files
=====================
2019-10-03 03:35:06 : Done orthologues
Orthogroups have been written to tab-delimited files:
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthogroups.csv
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthogroups.txt (OrthoMCL format)
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthogroups_UnassignedGenes.csv

Sequences for orthogroups:
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthologues_Oct03/Sequences

Multiple sequence alignments:
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthologues_Oct03/Alignments

Gene trees:
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthologues_Oct03/Gene_Trees/

Rooted species tree:
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthologues_Oct03/SpeciesTree_rooted.txt

Species-by-species orthologues:
   /scratch/cgsb/coruzzi/jh6577/GenomeFile/oth/Results_Oct02/Orthologues_Oct03/Orthologues/

Orthogroup statistics:
   Statistics_PerSpecies.csv   Statistics_Overall.csv   Orthogroups_SpeciesOverlaps.csv

OrthoFinder assigned 29278 genes (35.1% of total) to 10838 orthogroups. Fifty percent of all genes were in orthogroups with 1 or more genes (G50 was 1) and were contained in the largest 23275 orthogroups (O50 was 23275). There were 10738 orthogroups with all species present and 7188 of these consisted entirely of single-copy genes.

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2015), Genome Biology 16:157

 If you use the species tree in your work then please also cite:
 Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
 Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101/267914

```

**Comment by davidemms** [comment] 2019-10-04 14:54
Hi Ji

The extra gene trees (with only 3 taxa) don't need to be resolved in order to work out orthologs and so they aren't added to the Recon_Gene_Trees directory since they'd be exactly the same. The trees for those extra orthogroups (i.e. with only 3 taxa) are not particularly informative, but if you want to see them then just refer to the ones in the Gene_Trees directory.

All the best
David

**Closed by davidemms** 2019-10-04 14:54 UTC

**Comment by timedreamer** [comment] 2019-10-04 18:12
Thank you for the clarification.
Best,
Ji
