### ISSUE TITLE
filtering-out non-informative sequences from alignments + running on cloud

### ISSUE THREAD

**Issue by assafwww** [davidemms/OrthoFinder#297] opened 2019-10-27 17:14 UTC
Hello Orthofinder team,

I had two issues with orthofinder data:
1) in my experience, the alignment created by mafft during orthofinder run ( -M msa mode), often include sequences with only few **aligned** aas, that are not informative. Therefore I would prefer to remove such sequences from the alignments.
2) I prefer to run the gene tree reconstruction step (-ot) out of the orthofinder pipline, using iqtree/raxml, and then to give the results as an input (-ft option), since this step requires a lot of time and memory resources, and I think cannot be executed efficiently otherwise.

As a workaround, I thought to do the following:
1. I first allow orthofinder to run using: -M msa, -ot setting, with the default and fast fasttee tool. 
2. Then,  out of orthofinder pipline:
a) I filter non-informative sequences from alignments.
b) using the filtered alignment, I ran Iqtree jobs on the cloud.
c) The resulting gene trees have the format: OG0000001_tree.txt, OG0000002_tree.txt. These are copied to a new Gene_Trees directory (yet, in case the alignments included only 2 sequences, a tree will be missing of course). The previous Gene_Trees  directory is moved from there.
3. Then I ran orthofinder -ft (which points to the directory that contains Gene_Trees directory, plus all other orthofinder directories), where -s includes a known species tree.

Though this seems to technically work, it seems that the orthofinder reconciliation trees I checked include the filtered sequences and are not based on the input tree I gave.
I guess that when orthofinder sees that the tree doesn't include all original sequences - it builds it's own trees (using dendroblast?).
So, I would be happy to understand how to ensure that orthofinder uses the gene-trees it gets even if some sequences are missing (noninfomative sequences).

thanks a lot,
Assaf

**Comment by davidemms** [comment] 2019-10-28 09:30
Hi Assaf

Your pipeline is essentially correct, but you'll just need to do the tree inference on the alignments from WorkingDirectory/Alignments_ids/ and replace the files in WorkingDirectory/Trees_ids/ with your newly generated trees, these are the files OrthoFinder works from. The files in Gene_Trees/ are just for the user to look at. 

If any of you orthogroups had 4 or more genes before and have fewer than 4 genes after then you'd have to refer to the original results for any orthologs, as OrthoFinder won't know you've done something funny to these orthogroups and so it won't have inferred orthologs for your second run.

All the best
David

**Comment by davidemms** [comment] 2019-10-28 09:54
Another suggestion for your proposed pipeline, rather than using -ft the first time I would probably let it run to the end. This last step is very fast in comparison with the previous steps (especially with the latest version) and by letting it run, you get the original ortholog inference for comparison, this is especially useful if you want to see the orthologs that are missing from your new analysis because you were no longer able to infer trees for some orthogroups as they ended up with too few seqeunces, as mentioned above.

**Comment by assafwww** [comment] 2019-10-28 11:08
Hi David,
Thanks a lot for the rapid response.
The trees I created were based on the WorkingDirectory/Alignments_ids data, yet indeed I did not update the WorkingDirectory/Trees_ids directory.
I'll let it run to the end at first, so I'll have the results for those genes/trees that were removed.

cheers, 
Assaf

**Comment by assafwww** [comment] 2019-10-30 22:09
I can report that this setting (orthofinder -ft, based on user trees output, as we spoke) worked successfully now.
Assaf

**Comment by davidemms** [comment] 2019-11-04 15:27
Hi Assaf

Thanks for letting me know. 

In terms of running STAG, I'm unable to reproduce the issue you mention. When I run it from outside the directory it works fine. E.g.

```
~/NOBACKUP/ExampleDataset/OrthoFinder/Results_Nov04_3$ python ~/workspace/Releases_OrthoFinder/Release-2.3.7/source/OrthoFinder_source/orthofinder/scripts/stag.py WorkingDirectory/SpeciesIDs.txt Gene_Trees/
*********************************************************
*                                                       *
*      STAG: Species Tree inference from All Genes      *
*                                                       *
*********************************************************

etc

Examined 325 trees
269 trees had all species present and will be used by STAG to infer the species tree
STAG species tree: /home/emms/NOBACKUP/ExampleDataset/OrthoFinder/Results_Nov04_3/STAG_ResultsNov04/SpeciesTree.tre
```

 Would you be able to provide the series of steps you performed to reproduce it from a fresh download.

Many thanks
David

**Comment by davidemms** [comment] 2019-11-18 10:25
Hi Assaf

I'll close this issue as the original question has been resolved. If you're able to reproduce the issue with STAG then please report the required steps on the STAG issues page: https://github.com/davidemms/STAG/issues and I can look into it.

All the best
David

**Closed by davidemms** 2019-11-18 10:25 UTC
