### ISSUE TITLE
diamond stuck at "Creating diamond database 1 of 4" in ExampleDataset

### ISSUE THREAD

**Issue by SinaedaA** [davidemms/OrthoFinder#139] opened 2018-03-06 09:08 UTC
Hi,

I'm trying to use OrthoFinder for the first time, read the whole manual, and saw that it was possible to use diamond as the search program which is amazing when working with huge datasets. 
However, when I try to add the "-S diamond" option on the ExampleDataset, it gets stuck at the first step of creating the diamond database.
When I try to use OrthoFinder with either blast (default) or blast_gz, there is no problem at all.

I am working with the source script orthofinder.py, because the other option didn't work on my macbook.
My python version is 2.7.10
My diamond version is 0.9.9
`OrthoFinder-2.2.0/orthofinder/orthofinder.py -f OrthoFinder-2.2.0/orthofinder/ExampleDataset/ -og -S diamond`

Do you have any idea what the problem could be? As it is my first time, it is very probable that the issue is very easy to resolve, but I haven't found the solution yet :)
Thanks in advance !
Sina

**Comment by davidemms** [comment] 2018-03-06 12:13
Hi Sina

Can you run a diamond search outside of OrthoFinder? The commands OrthoFinder expects to be able to run are like this (using the example dataset):
`diamond makedb --in Mycoplasma_agalactiae.faa -d Species1`
and 
`diamond blastp -d Species1 -q Mycoplasma_hyopneumoniae.faa -o res_1_0.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1`

What happens If you try to run these from the directory containing the example files? (In fact, it would be better to copy the files to a different directory and try and run diamond there so as not to create extra files in the ExampleDataset directory)

All the best
David

**Comment by SinaedaA** [comment] 2018-03-06 12:40
Wow thank you for the fast response !
Yesterday I tried to do the makedb part of diamond and it worked, hence (silly me) I didn't look further into it. Here again I did what you suggested, and the makedb command does not return any error, and it does create the Species.dmnd database file.
However, running the blastp command returns the following error:
`Bus error: 10`
From what I see on the internet it might be related to diamond trying to modify some strings that are read-only, but I've never encountered this error before so I really don't know...

Have a nice day !
Sina

**Comment by davidemms** [comment] 2018-03-06 14:04
No problem! Would you be able to submit an issue on the DIAMOND github page: https://github.com/bbuchfink/diamond/issues. They should be able to help and it'd be useful for anyone else who sees a similar issue.

Thanks
David

**Comment by SinaedaA** [comment] 2018-03-06 15:00
Actually, I've just reinstalled a more recent version of diamond, and now the diamond command works fine.
So I was really optimistic about the outcome in OrthoFinder, but I keep getting the same problem (it is still stuck at the database creation).
Should I still ask this question on the DIAMOND github page, as it seems to be more related to OrthoFinder? 

I'm so sorry to keep bothering you, and I am very grateful for your help,
Sina

**Comment by davidemms** [comment] 2018-03-06 17:23
That's odd. Would you be able to post the output you get when you run the two diamond commands and then the output you get when you try to run OrthoFinder using DIAMOND.

**Comment by SinaedaA** [comment] 2018-03-07 09:19
Sure, sorry for the late response !

`diamond makedb --in Mycoplasma_agalactiae.faa -d Species1`
output:
```
diamond v0.9.18.119 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: Mycoplasma_agalactiae.faa
Opening the database file...  [0.058295s]
Loading sequences...  [0.004695s]
Masking sequences...  [0.040384s]
Writing sequences...  [0.001488s]
Loading sequences...  [2.2e-05s]
Writing trailer...  [2.8e-05s]
Closing the input file...  [3.7e-05s]
Closing the database file...  [0.000264s]
Processed 820 sequences, 295442 letters.
Total time = 0.105396s
```
For the diamond blastp command I removed the `quiet` option, in order to actually get something in the output.
`diamond blastp -d Species1 -q Mycoplasma_hyopneumoniae.faa -o res_1_0.txt --more-sensitive -p 1 -e 0.001 --compress 1`
output:
```
diamond v0.9.18.119 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory:
Opening the database...  [0.000118s]
Opening the input file...  [4.5e-05s]
Opening the output file...  [0.000221s]
Loading query sequences...  [0.002993s]
Masking queries...  [0.094316s]
Building query seed set...  [0.000407s]
Algorithm: Double-indexed
Building query histograms...  [0.052207s]
Allocating buffers...  [4.2e-05s]
Loading reference sequences...  [0.00103s]
Building reference histograms...  [0.054473s]
Allocating buffers...  [5.2e-05s]
Initializing temporary storage...  [0.047102s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.011066s]
Building query index...  [0.009424s]
Building seed filter...  [0.002276s]
Searching alignments...  [0.00618s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [0.008579s]
Building query index...  [0.007704s]
Building seed filter...  [0.002565s]
Searching alignments...  [0.006364s]
```
(...)
```
Processing query chunk 0, reference chunk 0, shape 15, index chunk 3.
Building reference index...  [0.00837s]
Building query index...  [0.007273s]
Building seed filter...  [0.00303s]
Searching alignments...  [0.008202s]
Deallocating buffers...  [1e-05s]
Computing alignments...  [0.503191s]
Deallocating reference...  [1.6e-05s]
Loading reference sequences...  [3.6e-05s]
Deallocating buffers...  [9e-06s]
Deallocating queries...  [1e-05s]
Loading query sequences...  [1.5e-05s]
Closing the input file...  [3.2e-05s]
Closing the output file...  [0.0011s]
Closing the database file...  [1.7e-05s]
Total time = 2.41472s
Reported 1091 pairwise alignments, 1136 HSPs.
416 queries aligned.
```

Then when I try it with OrthoFinder:
`OrthoFinder-2.2.0/orthofinder/orthofinder.py -f OrthoFinder-2.2.0/orthofinder/ExampleDataset/ -og -S diamond`
```
OrthoFinder version 2.2.0 Copyright (C) 2014 David Emms

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-03-07 10:04:22 : Creating diamond database 1 of 4
```

And it just gets stuck and doesn't do anything after this...

**Comment by davidemms** [comment] 2018-03-07 10:35
No problem, thanks. That's really odd, I can't think what could be going on. 

In the orthofinder.py file on line 1345 it says "util.RunCommand(command, qHideOutput=True)". Would you be able to change that to "qHideOutput=False" and then run it again. That way we'll be able to see if diamond is outputting anything when OrthoFinder tries to run it.

**Comment by SinaedaA** [comment] 2018-03-07 11:35
Oh I thought maybe it could be interesting to give you the message I get when cancelling the job with Ctrl C. So here it is: 
```
OrthoFinder version 2.2.0 Copyright (C) 2014 David Emms

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-03-07 10:04:22 : Creating diamond database 1 of 4
^CTraceback (most recent call last):
  File "OrthoFinder-2.2.0/orthofinder/orthofinder.py", line 1542, in <module>
    CreateSearchDatabases(dirs, options, program_caller)
  File "OrthoFinder-2.2.0/orthofinder/orthofinder.py", line 1345, in CreateSearchDatabases
    util.RunCommand(command, qHideOutput=True)
  File "/Users/sinaeda/Documents/bioinfo/orthofinder/OrthoFinder-2.2.0/orthofinder/scripts/util.py", line 79, in RunCommand
    subprocess.call(command, env=my_env, shell=qShell, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sinaeda/Documents/bioinfo/orthofinder/OrthoFinder-2.2.0/orthofinder/scripts/parallel_task_manager.py", line 66, in _I_Spawn_Processes
    time.sleep(4) # there wasn't anything this time, sleep then try again
KeyboardInterrupt
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

I changed the code as you suggested, and renamed it orthofinder_test.py (so I wouldn't forget that I had changed it).
`OrthoFinder-2.2.0/orthofinder/orthofinder_test.py -f OrthoFinder-2.2.0/orthofinder/ExampleDataset/ -og -S diamond`
Aaaaand... IT WORKED! I have no idea why, but it seems to have worked fine. Here is the output:

```
OrthoFinder version 2.2.0 Copyright (C) 2014 David Emms

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-03-07 12:28:52 : Creating diamond database 1 of 4
diamond v0.9.18.119 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: /Users/sinaeda/Documents/bioinfo/orthofinder/OrthoFinder-2.2.0/orthofinder/ExampleDataset/Results_Mar07_1/WorkingDirectory/Species0.fa
Opening the database file...  [0.008922s]
Loading sequences...  [0.00257s]
Masking sequences...  [0.037891s]
Writing sequences...  [0.001031s]
Loading sequences...  [1.8e-05s]
Writing trailer...  [4e-05s]
Closing the input file...  [4.7e-05s]
Closing the database file...  [0.000459s]
Processed 820 sequences, 295442 letters.
Total time = 0.051139s
2018-03-07 12:28:52 : Creating diamond database 2 of 4
diamond v0.9.18.119 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: /Users/sinaeda/Documents/bioinfo/orthofinder/OrthoFinder-2.2.0/orthofinder/ExampleDataset/Results_Mar07_1/WorkingDirectory/Species1.fa
Opening the database file...  [0.007833s]
Loading sequences...  [0.002837s]
Masking sequences...  [0.038129s]
Writing sequences...  [0.000848s]
Loading sequences...  [2.1e-05s]
Writing trailer...  [2.8e-05s]
Closing the input file...  [6.1e-05s]
Closing the database file...  [0.000283s]
Processed 763 sequences, 297398 letters.
Total time = 0.050198s
2018-03-07 12:28:52 : Creating diamond database 3 of 4
diamond v0.9.18.119 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: /Users/sinaeda/Documents/bioinfo/orthofinder/OrthoFinder-2.2.0/orthofinder/ExampleDataset/Results_Mar07_1/WorkingDirectory/Species2.fa
Opening the database file...  [0.006571s]
Loading sequences...  [0.001978s]
Masking sequences...  [0.021792s]
Writing sequences...  [0.000634s]
Loading sequences...  [2.1e-05s]
Writing trailer...  [2.1e-05s]
Closing the input file...  [3.1e-05s]
Closing the database file...  [0.00025s]
Processed 476 sequences, 175532 letters.
Total time = 0.031451s
2018-03-07 12:28:52 : Creating diamond database 4 of 4
diamond v0.9.18.119 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: /Users/sinaeda/Documents/bioinfo/orthofinder/OrthoFinder-2.2.0/orthofinder/ExampleDataset/Results_Mar07_1/WorkingDirectory/Species3.fa
Opening the database file...  [0.007604s]
Loading sequences...  [0.002291s]
Masking sequences...  [0.034465s]
Writing sequences...  [0.001107s]
Loading sequences...  [6.4e-05s]
Writing trailer...  [9.7e-05s]
Closing the input file...  [5.9e-05s]
Closing the database file...  [0.000379s]
Processed 674 sequences, 262963 letters.
Total time = 0.046284s

Running diamond all-versus-all
------------------------------
Using 16 thread(s)
2018-03-07 12:28:52 : This may take some time....
2018-03-07 12:28:52 : Done 0 of 16

Running OrthoFinder algorithm
-----------------------------
2018-03-07 12:29:12 : Initial processing of each species
2018-03-07 12:29:13 : Initial processing of species 0 complete
2018-03-07 12:29:13 : Initial processing of species 1 complete
2018-03-07 12:29:13 : Initial processing of species 2 complete
2018-03-07 12:29:14 : Initial processing of species 3 complete
2018-03-07 12:29:18 : Connected putatitive homologs
2018-03-07 12:29:18 : Written final scores for species 0 to graph file
2018-03-07 12:29:18 : Written final scores for species 1 to graph file
2018-03-07 12:29:19 : Written final scores for species 2 to graph file
2018-03-07 12:29:19 : Written final scores for species 3 to graph file
2018-03-07 12:29:20 : Ran MCL

Writing orthogroups to file
---------------------------

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2015), Genome Biology 16:157

Orthogroups have been written to tab-delimited files:
   /Users/sinaeda/Documents/bioinfo/orthofinder/OrthoFinder-2.2.0/orthofinder/ExampleDataset/Results_Mar07_1/Orthogroups.csv
   /Users/sinaeda/Documents/bioinfo/orthofinder/OrthoFinder-2.2.0/orthofinder/ExampleDataset/Results_Mar07_1/Orthogroups.txt (OrthoMCL format)
   /Users/sinaeda/Documents/bioinfo/orthofinder/OrthoFinder-2.2.0/orthofinder/ExampleDataset/Results_Mar07_1/Orthogroups_UnassignedGenes.csv
2018-03-07 12:29:20 : Done orthogroups

Orthogroup statistics:
   Statistics_PerSpecies.csv   Statistics_Overall.csv   Orthogroups_SpeciesOverlaps.csv

OrthoFinder assigned 1779 genes (65.1% of total) to 507 orthogroups. Fifty percent of all genes were in orthogroups with 3 or more genes (G50 was 3) and were contained in the largest 322 orthogroups (O50 was 322). There were 269 orthogroups with all species present and 248 of these consisted entirely of single-copy genes.

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2015), Genome Biology 16:157
```

I don't think there is anything wrong with it now, what do you think?
Thank you SO MUCH for all the help !

**Comment by davidemms** [comment] 2018-03-07 12:57
No problem. Agreed, it seems to be running fine. 

It's odd, I'm not sure why printing the output would make a difference but I'll post here if I find a way of fixing it without that. For the time being though running it with just that change in seems the best solution.

All the best
David

**Comment by SinaedaA** [comment] 2018-03-07 12:59
I don't really understand what happened either, but I'm happy it works.
I will run it like this for the time being !
Again, thanks a lot for taking the time to look for a solution with me, I really appreciate it.

All the best,
Sina

**Comment by Juassis** [comment] 2018-12-04 16:15
Hi,
I have the same problem here, however, change the line In the orthofinder.py file on line 1345 (1410 into the new version) didn't work to me.

    `            command = program_caller.GetSearchMethodCommand_DB(options.search_program, scripts.files.FileHandler.GetSpeciesFastaFN(iSp), scripts.files.FileHandler.GetSpeciesDatabaseN(iSp, options.search_program))
            util.PrintTime("Creating %s database %d of %d" % (options.search_program, iSp + 1, nDB))
            util.RunCommand(command, qHideOutput=False)`


If I run the orthofinder in the same directory it works very well, but if I try to run in a different dir, even using the Example data, It does not work.

Also, for linux it works.
##########################################################
Diamond test:
Mac-mini-de-Juliana:ExampleData Juliana$ diamond makedb --in Mycoplasma_agalactiae.faa -d Species1
diamond v0.9.21.122 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: Mycoplasma_agalactiae.faa
Opening the database file...  [0.001922s]
Loading sequences...  [0.003825s]
Masking sequences...  [0.031957s]
Writing sequences...  [0.001449s]
Hashing sequences...  [0.000136s]
Loading sequences...  [1.3e-05s]
Writing trailer...  [7.7e-05s]
Closing the input file...  [3.6e-05s]
Closing the database file...  [0.000191s]
Database hash = 873a10aafcdf0638667d7c5bd5f21fe7
Processed 820 sequences, 295442 letters.
Total time = 0.039751s
Mac-mini-de-Juliana:ExampleData Juliana$ diamond blastp -d Species1 -q Mycoplasma_hyopneumoniae.faa -o res_1_0.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Mac-mini-de-Juliana:ExampleData Juliana$ 

#############################################################
Error:
          command = program_caller.GetSearchMethodCommand_DB(options.search_program, scripts.files.FileHandler.GetSpeciesFastaFN(iSp), scripts.files.FileHandler.GetSpeciesDatabaseN(iSp, options.search_program))
            util.PrintTime("Creating %s database %d of %d" % (options.search_program, iSp + 1, nDB))
            util.RunCommand(command, qHideOutput=False)

python2.7 OrthoFinder-2.3.1_source/orthofinder/orthofinder.py -f /PROTEINS/

OrthoFinder version 2.3.1 Copyright (C) 2014 David Emms

2018-12-03 16:37:02 : Starting OrthoFinder
4 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------

ERROR: Cannot run diamond
Format of make database command:
  diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
  diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path

ERROR: An error occurred, please review error messages for more information.

Many thanks
Juliana

**Comment by Juassis** [comment] 2018-12-05 20:54
Hi!
I have the same problem using the OS (for Linux it works).
However, changing the line 1410 (new version) didn't work for me.
`            command = program_caller.GetSearchMethodCommand_DB(options.search_program, scripts.files.FileHandler.GetSpeciesFastaFN(iSp), scripts.files.FileHandler.GetSpeciesDatabaseN(iSp, options.search_program))
            util.PrintTime("Creating %s database %d of %d" % (options.search_program, iSp + 1, nDB))
            util.RunCommand(command, qHideOutput=True)`

The other point is: if I run the orthofinder.py and the input files are inside the orthofinder directory, the program works. However, if I put the input files in a different directory I encounter the following error message:

    command = program_caller.GetSearchMethodCommand_DB(options.search_program, scripts.files.FileHandler.GetSpeciesFastaFN(iSp), scripts.files.FileHandler.GetSpeciesDatabaseN(iSp, options.search_program))
            util.PrintTime("Creating %s database %d of %d" % (options.search_program, iSp + 1, nDB))
            util.RunCommand(command, qHideOutput=False)

python2.7 OrthoFinder-2.3.1_source/orthofinder/orthofinder.py -f /PROTEINS/

OrthoFinder version 2.3.1 Copyright (C) 2014 David Emms

2018-12-03 16:37:02 : Starting OrthoFinder
4 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------

ERROR: Cannot run diamond
Format of make database command:
  diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
  diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path

ERROR: An error occurred, please review error messages for more information.


#############################################
Following your recommendation:
"Can you run a diamond search outside of OrthoFinder? The commands OrthoFinder expects to be able to run are like this (using the example dataset):"

Mac-mini-de-Juliana:ExampleData Juliana$ diamond makedb --in Mycoplasma_agalactiae.faa -d Species1
diamond v0.9.21.122 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: Mycoplasma_agalactiae.faa
Opening the database file...  [0.001922s]
Loading sequences...  [0.003825s]
Masking sequences...  [0.031957s]
Writing sequences...  [0.001449s]
Hashing sequences...  [0.000136s]
Loading sequences...  [1.3e-05s]
Writing trailer...  [7.7e-05s]
Closing the input file...  [3.6e-05s]
Closing the database file...  [0.000191s]
Database hash = 873a10aafcdf0638667d7c5bd5f21fe7
Processed 820 sequences, 295442 letters.
Total time = 0.039751s
Mac-mini-de-Juliana:ExampleData Juliana$ diamond blastp -d Species1 -q Mycoplasma_hyopneumoniae.faa -o res_1_0.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Mac-mini-de-Juliana:ExampleData Juliana$ 

########################
Do you have any idea how to fix it? I'd like to run the orthofinder.py in a different dir of orthofinder.
Many thanks
Juliana Assis

**Comment by davidemms** [comment] 2018-12-06 16:08
Hi Juliana

Where diamond executable? Could it be that it's not in the system path and so the system can't find it if you're in a different directory?

All the best
David

**Comment by Juassis** [comment] 2018-12-06 23:31
Hi David

Diamond is in the system path. I can run diamond in a different dir,  but I can’t when I’m using orthofinder.
I’m trying to figure out what is wrong, but I have no idea.

I’ve been using orthofinder for while, however since I’ve updated the OS to Mojave it is happening.

Many thanks 
Juliana
Enviado do meu iPhone

Em 6 de dez de 2018, à(s) 14:08, David Emms <notifications@github.com> escreveu:

**Comment by davidemms** [comment] 2018-12-07 12:47
Hi Juliana

The latest changes to the orthofinder code now print out the output orthofinder gets from diamond if there are any problems. That might help identify what the problem is.

All the best
David

**Comment by Juassis** [comment] 2018-12-07 17:22
Hi David,

I'll let you know when I figure out what is happening with the new version (OrthoFinder-2.3.1_source) in my Mac mini, also I'll try using a different computer. For CentOS Linux release 7.4.1708 (Core) I have no problem. 

For now, I decided to work with the  OrthoFinder-2.2.7_source version.  This version works perfectly on MacOS.

I have a dumb question:
How does the orthofinder decide which species will be represented in the first column of the output file?  Can we define the species to be displayed first? This information is important to my pipeline, currently, I'm forcing alphabetic ordering.

Thanks again
Juliana

**Comment by davidemms** [comment] 2019-01-23 16:32
Hi Juliana

The filenames are currently sorted in ascii order (e.g. all uppercase letters will come before any lower case ones). 

All the best
David

**Comment by davidemms** [comment] 2019-04-29 15:03
Following up on the issue that SinaedaA reports at the top of this thread, I believe this is the same as https://github.com/davidemms/OrthoFinder/issues/145 and that the fix there resolves this issue.

**Closed** 2019-04-29 15:05 UTC
