### ISSUE TITLE
GNU libc v2.18 required in OrthoFinder v2.3.3

### ISSUE THREAD

**Issue by Neato-Nick** [davidemms/OrthoFinder#263] opened 2019-05-20 18:29 UTC
Hi,

I've been running OrthoFinder version 2.2.7 and wanted to upgrade to the newest version. It appears to crash and then hang until I kill the process, with the error at the bottom of this post. It looks like I need at least GNU libc 2.18, and since I'm running this on my institution’s HPC, I'm stuck with libc 2.17.

The OrthoFinder v2.3.1 beta release executes properly on the HPC, and v2.3.3 works on a local install (running GLIBC 2.23). I'm only struggling to run the newest release on the HPC.

Is there any way to work around the libc 2.18 requirement? Or is there a different issue going on here?
```
$ OrthoFinder-2.3.3/orthofinder -h
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 39, in <module>
  File "/tmp/pip-install-CVqmNG/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/scipy/optimize/__init__.py", line 387, in <module>
  File "/tmp/pip-install-CVqmNG/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/scipy/optimize/_minimize.py", line 30, in <module>
  File "/tmp/pip-install-CVqmNG/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/scipy/optimize/_trustregion_constr/__init__.py", line 4, in <module>
  File "/tmp/pip-install-CVqmNG/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 4, in <module>
  File "/tmp/pip-install-CVqmNG/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/scipy/sparse/__init__.py", line 231, in <module>
  File "/tmp/pip-install-CVqmNG/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/scipy/sparse/csr.py", line 15, in <module>
  File "/tmp/pip-install-CVqmNG/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 684, in load_module
ImportError: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /data/_MEIdG4X8Z/libstdc++.so.6)
[9991] Failed to execute script orthofinder
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
Process Process-1:
  File "atexit.py", line 24, in _run_exitfuncs
  File "multiprocessing/util.py", line 328, in _exit_function
Traceback (most recent call last):
  File "multiprocessing/process.py", line 148, in join
  File "multiprocessing/process.py", line 267, in _bootstrap
  File "multiprocessing/forking.py", line 154, in wait
  File "multiprocessing/forking.py", line 135, in poll
KeyboardInterrupt
  File "multiprocessing/process.py", line 114, in run
Error in sys.exitfunc:
  File "orthofinder/scripts/parallel_task_manager.py", line 72, in _I_Spawn_Processes
KeyboardInterrupt
Traceback (most recent call last):
  File "atexit.py", line 24, in _run_exitfuncs
  File "multiprocessing/util.py", line 328, in _exit_function
  File "multiprocessing/process.py", line 148, in join
  File "multiprocessing/forking.py", line 154, in wait
  File "multiprocessing/forking.py", line 135, in poll
KeyboardInterrupt
```

**Comment by davidemms** [comment] 2019-05-29 09:07
Hi Nick, I'll look into doing this.

All the best
David

**Comment by davidemms** [comment] 2019-05-30 09:46
Hi Nick

GLIBC 2.17 is really old! Is your institution's HPC still getting security updates? I set up a virtual machine with Ubuntu 14.04 LTS to build a suitable orthofinder package, but even that, which is 5 years old and no longer supported, used version 2.19. Version 2.17 was released in 2012. 

Anyway, it looks like OrthoFinder 2.3.1 was built to use glibc version 2.19. As that worked on your HPC I've gone ahead created an orthofinder package based on that, using the Ubuntu 14.04 virtual machine. It's available on the releases page: https://github.com/davidemms/OrthoFinder/releases/tag/2.3.3. If that doesn't work for you then let me know and I can try and install a linux distribution with an older glibc to create a package which only needs an older version of glibc.

The other alternative is to use the source code version of OrthoFinder. That has no dependency on any particular versions of glibc.

All the best
Davidcd

**Comment by Neato-Nick** [comment] 2019-05-30 20:33
Weird! Our HPC still gets regular updates and seems to be pretty on top of security. I wonder if upgrading glibc is something they should be looking into regardless.

As for orthofinder, that _glibc-2.19 version didn't work. Got the same error as reported earlier. Weird that the pre-compiled 2.3.1 works and 2.3.3 doesn't, even though they require the same glibc version.

As you suggested, downloading the source code from the 2.3.3 release, uncompressing it, and executing it as 

`$ OrthoFinder-2.3.3/orthofinder/orthofinder.py -h`

did work as expected. This is a good solution for me. Thanks!

**Comment by davidemms** [comment] 2019-05-31 08:47
Hi Nick

It's great that the source code version is working for you. Thanks for trying out the binary version and letting me know. I'll probably try and create a version using glibc 2.17 just in case it's a problem for anyone else.

All the best
David

**Comment by qisun2** [comment] 2019-06-07 12:52
We have the same glibc problem here. The university HPC centers in general use CentOS not Ubuntu,  and gblic 2.17 is the latest on CentOS. As glib is tied to the system, it cannot be changed.  Is there performance advantage of using the binary vs the python script? If the same, we could just use the python script.

**Comment by davidemms** [comment] 2019-06-07 13:12
There is no performance advantage, the only advantage of the binary is that it packages the numpy and scipy libraries so the user doesn't have to install them themselves. That's the only reason I suggest it to new users. In general, the source code version is good choice.

All the best
David

**Comment by qisun2** [comment] 2019-06-07 13:16
Thanks! We will use the source then.

**Comment by davidemms** [comment] 2019-06-11 12:19
Hi

Thanks for the tip on CentOS, I've now created a virtual machine with that and built a version of the OrthoFinder package that relies on glibc 2.17. I'm not 100% certain that that it what the issue is but the package is here: https://github.com/davidemms/OrthoFinder/releases/tag/2.3.3 so if someone can have a try and let me know if it resolves the problem then that would be great. If it does then I will remove the 2.19 version and include a 2.17 dependent version in future releases--either as the default, or a separate, named one as I've done here.

All the best
David

**Comment by AriaLyu** [comment] 2019-06-12 13:23
Unluckyly, our university HPC centers also use CentOS, and the gblic-2.l4 is the lastest release that cannot update.

**Comment by davidemms** [comment] 2019-06-12 14:08
Hi AriaLyu

I think the source code version will be best for you--I downloaded the CentOS distribution and that comes with 2.17. I don't know of a current, supported distribution I can download that will give me an older version of glibc. 

The source code version uses the libraries already on your machine, you just need to have numpy and scipy installed, which I assume your university HPC already will.

All the best
David

**Comment by AriaLyu** [comment] 2019-06-13 01:34
Hi David,
Thanks for your help.The source code version is working for ours.
All the best
Aria

**Closed** 2019-06-14 08:48 UTC

**Comment by Neato-Nick** [comment] 2019-06-19 16:56
@davidemms no need to re-open this issue, just wanted to update you

> Thanks for the tip on CentOS, I've now created a virtual machine with that and built a version of the OrthoFinder package that relies on glibc 2.17. I'm not 100% certain that that it what the issue is but the package is here: https://github.com/davidemms/OrthoFinder/releases/tag/2.3.3 so if someone can have a try and let me know if it resolves the problem then that would be great.

I tried this build on my HPC and I didn't get any errors 💯  thanks!
