### ISSUE TITLE
Malformatted blast result error

### ISSUE THREAD

**Issue by ajwnewkirk** [davidemms/OrthoFinder#43] opened 2017-01-09 18:16 UTC
I've been running OrthoFinder successfully using both the included example files and a subset (~30) of the 266 genomes I eventually need to analyze. I'm including OrthoFinder as part of a larger pipeline, so I'm gradually scaling up and I build things out. 

Last week I tried to run the full 266 genome set for the first time, and I got an error in the step where all of the blast results are being processed for each genome (Date time : Initial processing of species # complete). The error was "Malformatted line in /path/Blast#_#.txt, offending line was: ..."

It appeared that the error might be related to Issue #31, so I updated my installation to the current release (1.1.2). I am using MCL-edge/14-137 and ncbi-blast+/2.3.0. I'm only interested in orthogroup inference, so I am not using any other dependencies.

When I retried the same set of genomes, I got a similar error.
```
2017-01-08 17:33:05 : Initial processing of species 186 complete
2017-01-08 17:35:50 : Initial processing of species 187 complete
2017-01-08 17:38:30 : Initial processing of species 188 complete
Malformatted line in /scicomp/home/igy7/git-repos/ts4/results/aaORFs/Results_Jan06/WorkingDirectory/Blast189_45.txt
Offending line was:
189_3812        45_1697 22.273  220     156     8       474     679     8       226     0.001   38.5
ERROR: An error occurred, please review previous error messages for more information.
```

When I reviewed the file Blast189_45.txt, this is what I found:
```
189_3812        45_1697 22.273  220     156     8       474     679     8       226     0.001   38.5
189_3813        45_4358 98.436  5561    85^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@189_3814    45_4357 99.765  425     1       0       1       425     1       425     0.0     842
189_3814        45_820  22.857  420     246     15      10      408     27      389     3.54e-16        77.0
189_3814        45_4357 99.765  425     1       0       1       425     1       425     0.0     842
189_3814        45_820  22.857  420     246     15      10      408     27      389     3.54e-16        77.0
```
So 189_3813 seems to be the real problem. When I ran `grep 45_4358 Blast45_189.txt`, the results seem normal.
```
45_4358 189_3813        98.436  5561    85      1       1       5559    1       5561    0.0     10909
```

The fasta input files for both of these appear normal to me. Any suggestions?

Thank you!

**Comment by ajwnewkirk** [comment] 2017-01-09 19:31
The fasta records in question, in case it's helpful.

```
>189_3813
MDKKLEPYYLSAETALSIVSKKFNIKIDIKEDDINLRFKKYDRNNTDDSIQMKNFFLSLGLSLQDILFNNGEDLLNEPMPILLLTPEMKWMVCVSGGQKIKLVNARGELCYVEIEDEYLKELSAFSILPLNKVVDSIRVKNIIKNSLSMNKIFYTKYFFSSLFMAIFALTIPVFSNLFYDKLVPSASVSSLFGVAIIVAVFIVFEFILRTSKDIYQSITARQDDVDIDIAFLEAVLYSKKKNGRSMSSAFVLWNEFQKIKPVLLNSIFQRIADIPIFIIFLIVIYVNLGLVVIVPVTMFIVSIIISLVNHHYTNELMNKQKEGQKNRNIFISEVFLSIKMIHTLNNQGLLFDWVNTSNEQSYLNLKIRKLNLIYQSILGSMSSVTQITIMVIAFFMVIKGDVTTGAIVSSVIVSGRISGIISNFSSTLISILSAEKTGKDLLSFFDEDQAEKTPALQSISKCNGDISIRGVSYQYDAQSPMIINRLSIDIPAGQRVAVIGECGAGKSSLLGMLSGYLSPTDGAILYDGYNLGHLSQNFFSQHLSVVTTHDVLFTGTIESNFALKPQNDRGRVLKALHLANCGFILQHPMGLKFPVNFMAKNLSSGQQQQLLLARSLSSNASVFLWDEPTSNLDENTEKQIFDNLDEFIHGKTLIMVTHRRYLIKYFDRVLVMKGGKIIRDCSPDKLLM
>45_4358
MNRRQSDHLMMIIISLTILIIILTYFIEINSVVHGQGVITTKDNAQLISLSKGGTIQDIYVAEGDTVKKGELLAKVVNLDLQKEYQRYRTQKGYLDKDVNEISFILDKENESGLITLDGTRSLSNKEVKANIELVHSQIRAKELKKTSLDSEISGLQEKLSSKEKELALLAEEINILSPLVKKGISPYTNFLNKKQTYIKVKSEINDIESSITLKKDDIELVVNDIEALNNELRLSLSKIISKNLQELEVVNSTLKVIEKQINEEDIYSPVDGVIYKINKSATTHGGVIQAADLLFEIKPKVRTMLADVKILPKYRDQIYVDEAVKLDVQSIIQPKIKSYNATIDNISPDSYEENTGGTIQRYYKVIIAFDVNEDDLRWLKPGMTVDASVITGKHSIMEYLLSPLMKGVDKAFSEPVNTKRLDTP
```

**Comment by mdebiasse** [comment] 2017-02-06 20:46
I am encountering a similar problem in OrthoFinder version 1.1.4 with blast version 2.4.0. 
The errors read: 

```
ERROR: Query or hit sequence ID in BLAST results file was missing or incorrectly formatted.
Malformatted line in /mdebiasse/05-OrthoFinder/Blast37_0.txt
Offending line was:
106     58      1       84      189     1       101     1.31e-21        84.0

ERROR: Query or hit sequence ID in BLAST results file was missing or incorrectly formatted.
Malformatted line in /mdebiasse/05-OrthoFinder/Blast17_37.txt
Offending line was:
22064   37_42994        25.339  221     139     6       20      238     3       199     4.23e-12        67.0
```
In the first example, 3 columns are missing from the line (query name, subject name, and percent identity) and in the second example, the name of the query was truncated- it should be 17_22064. There is variation in how much of the problem line is missing across all my misformatted files.

I split my blast searches over two machines and interestingly, the runs with blast 2.2.31 are all ok. 12 of 15 runs with blast 2.4.0 have errors. Seems like this is a problem with blast, not OrthoFinder.

**Comment by davidemms** [comment] 2017-03-20 17:21
Hi 

Yes the problem is in the results file being produced by blastp, the question is why is it occurring? OrthoFinder isn't doing anything special to create the blast results file, in the case reported by ajwnewkirk it is just calling 
`blastp -outfmt 6 -evalue 0.001 -query Species189.fa -db BlastDBSpecies45 -out Blast189_45.txt`
for the files in the directory 
`/scicomp/home/igy7/git-repos/ts4/results/aaORFs/Results_Jan06/WorkingDirectory/`

I'd recommend that you try calling this command yourself and seeing if you get the same problem in the result file Blast189_45.txt (it'd probably be a good idea to save a copy of the original file). If the problem goes away you can just check that no other files have a similar problem (can you search for the ^@ character?) and then run OrthoFinder from your blast results using the -b option. If the problem does reoccur then there is something odd going on in blast that needs to be looked into. I'd be very interested to know what happens!

All the best
David

**Comment by davidemms** [comment] 2017-03-20 17:22
... obviously, another option is just to correct the malformatted line and run orthofinder from these blast results files using the -b option.

**Comment by davidemms** [comment] 2017-03-20 17:35
Hi mdebiasse

I wonder if one possibility could be that you are simultaneously running blastp twice to the same output file and so the output is garbled if they try and write a line at the same time? Or something similar? I've had problems before when I've been running lots of blast searches manually and I've concatenated blast results files together incorrectly or when I've accidentally stopped blast prematurely rather than it turning out to be a problem with blast! Can you think of anything that could have caused the results files to have got messed up?

All the best
David

**Comment by aleksberic** [comment] 2018-03-26 13:08
Hi,
I am having a similar issue. The error I get is:
2018-03-26 07:08:30 : Initial processing of each species
Malformatted line in /path/Results_Mar23/WorkingDirectory/Blast0_0.txt
Offending line was:

Process Process-2:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
  File "orthofinder/scripts/blast_file_processor.py", line 63, in GetBLAST6Scores
Error: line contains NULL byte
Malformatted line in /path/Results_Mar23/WorkingDirectory/Blast1_0.txt
Offending line was:
 
It shoots out the same error message for all the subsequent Blast#_0.txt files. However, as shown above, it doesn't report an offending line in either case. I am using the latest version of orthofinder, and the latest version of diamond.

I'd appreciate any help.

Thank you,
Aleksandra

**Comment by davidemms** [comment] 2018-03-26 14:03
Hi Aleksandra

From the message it looks like you might have blank lines in your Blast#_0.txt files, is that the case?

Did you do the diamond searches yourself (and then orthofinder with the -b option) or did you do everything in orthofinder (-f option)?

All the best
David

**Comment by aleksberic** [comment] 2018-03-26 20:32
Hi David,

Thanks for the quick response.

I use diamond as part of orthofinder (like this: orthofinder -a 16 -S diamond -f proteomes/).
It seems that the first line of each blast output file is incomplete, but they don't seem to have blank lines. 
I've also checked other blast output files (not just #_0, but also #_1, #_2, etc.), and there are issues with the first line in all the files. It almost looks like part of the output from start to x was deleted.

This is the first time for me trying to do this sort of analysis, so I don't really have an idea why this might be happening.

Thanks again,
Aleksandra

**Comment by rafaeltiveron** [comment] 2018-03-29 22:45
Yes, I've the same problem. I am using Diamond version 0.9.19.

**Comment by aleksberic** [comment] 2018-03-30 15:24
Hi,

Here is an update on my part after trying to run diamond prior to running orthofinder.

Diamond seems to work fine. However, when I try running orthofinder from pre-computed blast results, again I get the message:

Malformatted line in path/01-diamond_output/Blast6_0.txt
Offending line was:
15_27751	0_20382	59.8	527	179	10	22	522	5	524	2.9e-160	562.0

Malformatted line in path/01-diamond_output/Blast16_0.txt
Offending line was:
8_26346	0_21027	48.0	125	64	1	7	130	9	133	1.7e-27	119.0

These lines look like a standard blast output, and there don't seem to be any blank lines in any of my blast output files.
Diamond seems to work fine, so I'm not sure what might be the problem.

Aleksandra

**Comment by sejmodha** [comment] 2018-04-04 09:00
I get the same error with diamond v0.9.19.120. 


Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-04-04 09:49:32 : Creating diamond database 1 of 4
2018-04-04 09:49:32 : Creating diamond database 2 of 4
2018-04-04 09:49:32 : Creating diamond database 3 of 4
2018-04-04 09:49:32 : Creating diamond database 4 of 4

Running diamond all-versus-all
------------------------------
Using 16 thread(s)
2018-04-04 09:49:33 : This may take some time....
2018-04-04 09:49:33 : Done 0 of 16

Running OrthoFinder algorithm
-----------------------------
2018-04-04 09:51:45 : Initial processing of each species
Malformatted line in ../orthofinder_input/Results_Apr04_1/WorkingDirectory/Blast0_0.txt
Offending line was:

Process Process-18:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
  File "orthofinder/scripts/blast_file_processor.py", line 63, in GetBLAST6Scores
Error: line contains NULL byte
Malformatted line in ../orthofinder_input/Results_Apr04_1/WorkingDirectory/Blast2_0.txt
Offending line was:

Process Process-20:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
  File "orthofinder/scripts/blast_file_processor.py", line 63, in GetBLAST6Scores
Error: line contains NULL byte
Malformatted line in ../orthofinder_input/Results_Apr04_1/WorkingDirectory/Blast3_0.txt
Offending line was:

Process Process-22:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
  File "orthofinder/scripts/blast_file_processor.py", line 63, in GetBLAST6Scores
Error: line contains NULL byte
Malformatted line in ../orthofinder_input/Results_Apr04_1/WorkingDirectory/Blast1_0.txt
Offending line was:

Process Process-19:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
  File "orthofinder/scripts/blast_file_processor.py", line 63, in GetBLAST6Scores
Error: line contains NULL byte
ERROR: An error occurred, please review error messages for more information.

**Comment by aleksberic** [comment] 2018-04-04 15:41
Not even *.txt.gz? Maybe they are just compressed...mine were.

**Comment by rafaeltiveron** [comment] 2018-04-04 19:27
I've tested this hypothesis. I've got the same error. Extracted txt files have first line as NULL.

**Comment by rafaeltiveron** [comment] 2018-04-04 19:29
`ls` shows blast.txt.gz as blast.txt and execute as text file.

**Comment by sejmodha** [comment] 2018-04-05 11:00
Hi there,

Yes, I can confirm that the compressed files do exist in the specified location. What's the best way to ensure either a) uncompressed files are generated as diamond output, or b) uncompress the compressed output files?

Thanks for your help.

**Comment by aleksberic** [comment] 2018-04-05 12:33
Hi sejmodha,

I don't think it matters if the files are compressed, Orthofinder should still be able to use them. If you want to check if your blast output is defective however, you can run a simple gunzip *.gz command in the directory where they are located and investigate them further.

Also, I believe that diamond, when it's run independently, generates simple .txt output. This will generate new outputs for you, but might not be a good representation of what went wrong if the first time around you used diamond as orthofinder -S diamond -f directory/ command.

Best,
Aleksandra

**Comment by sejmodha** [comment] 2018-04-05 14:38
Hi,
I checked the content of the files and all files contain multiple lines of ` ^@^@` at the beginning of the file which seems to fail the OrthoFinder pipeline.

**Comment by davidemms** [comment] 2018-04-06 11:14
Hi

Does somebody have a small-ish dataset that this occurs on and would you be able to zip the WorkingDirectory up and send it to me so I can investigate? 

Thanks 
David

**Comment by davidemms** [comment] 2018-04-06 11:24
This seems to be a problem with recent diamond releases, I've reproduced it with the latest version, v0.9.19.120 using OrthoFinder's example dataset. I can confirm that v0.8.38.100 works fine (that's the last one I was using). If anyone knows about success/failure with intermediate releases could they post here so we can track down when the issue occurred and so that people know what versions are safe to use. I'll report the issue to the diamond developers.

Thanks all for reporting this.
David

**Comment by sejmodha** [comment] 2018-04-06 12:44
Hi David,

Thanks for confirming this. I was running OrthoFinder with diamond v0.9.19.120

Thanks for your help.
Sej

**Comment by rafaeltiveron** [comment] 2018-04-07 18:35
Thanks, David,

I've changed diamond version from 0.9.19.120 to 0.9.18. It seems this problem was resolved or not present. I think the problem is associated with the new algorithms for this: "This release changes the database format and requires database rebuilding. To rebuild the database from an existing one, a Unix pipe can be used like this:
/path/to/old/diamond getseq -d dbfile | /path/to/new/diamond makedb -d newdb"
https://github.com/bbuchfink/diamond/releases

I am running mcl step of orthofinder and if any other problem appears here, I'll inform.

**Comment by davidemms** [comment] 2018-04-20 07:12
This has now been fixed in the latest release of diamond

**Closed** 2018-04-24 14:07 UTC

**Comment by mariferrarini** [comment] 2018-05-13 13:14
Dear all,
I'm having the same issue with the Example Dataset, not sure how to fix the problem:
`
ERROR: Query or hit sequence ID in BLAST results file was missing or incorrectly formatted.
Malformatted line in /Programs/OrthoFinder-2.2.3/orthofinder/ExampleData/Results_May13_1/WorkingDirectory/Blast0_0.txt
Offending line was:
0_0	pdb|0_72|0	27.36	106	70	3	155	258	153	253	3e-07	48.1
Process Process-18:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, qDoubleBlast=qDoubleBlast)
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
    Bij = BlastFileProcessor.GetBLAST6Scores(seqsInfo, fileInfo, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
  File "/Programs/OrthoFinder-2.2.3/orthofinder/scripts/blast_file_processor.py", line 67, in GetBLAST6Scores
    sequence2ID = int(row[iH].split(sep, 1)[1])
ValueError: invalid literal for int() with base 10: '72|0'
ERROR: An error occurred, please review error messages for more information.
 
`

**Comment by mariferrarini** [comment] 2018-05-13 13:55
Dear all,

Problem with blast version is already solved, but I wanted to report it anyway, in the case someone is having it too.

Not sure why, I kept having the same error as reported above when running Orthofinder with BLAST 2.2.18+. When I installed the new BLAST 2.7.1+, this does not happen and Orthofinder runs smoothly.

The problem is as follows, but unlike any other users, I was running the ExampleDataset and I didn't find the same issues in the blast output files. Whenever I check and parse it there does not seem to be a problem with missing values or bizarre ^@ characters (attached there's output Blast0_0.txt, in case I'm missing something). However, it seems that there is a problem with the sequence names: blast outputs sequence name "pdb|0_72|0"  instead of 0_720 (and there are plenty of other sequence errors such as this one).

Below the ERROR message:

```
ERROR: Query or hit sequence ID in BLAST results file was missing or incorrectly formatted.
Malformatted line in /Programs/OrthoFinder-2.2.3/orthofinder/ExampleData/Results_May13_1/WorkingDirectory/Blast0_0.txt
Offending line was:
0_0	pdb|0_72|0	27.36	106	70	3	155	258	153	253	3e-07	48.1
Process Process-18:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, qDoubleBlast=qDoubleBlast)
  File "orthofinder/orthofinder.py", line 471, in ProcessBlastHits
    Bij = BlastFileProcessor.GetBLAST6Scores(seqsInfo, fileInfo, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
  File "/Users/mdesouzafe/Programs/OrthoFinder-2.2.3/orthofinder/scripts/blast_file_processor.py", line 67, in GetBLAST6Scores
    sequence2ID = int(row[iH].split(sep, 1)[1])
ValueError: invalid literal for int() with base 10: '72|0'
```
[Blast0_0.txt](https://github.com/davidemms/OrthoFinder/files/1998484/Blast0_0.txt)

The sequenceIDs.txt and species0.fa file seem ok (with sequence 0_720 displayed correctly):

[SequenceIDs.txt](https://github.com/davidemms/OrthoFinder/files/1998495/SequenceIDs.txt)
[Species0.txt](https://github.com/davidemms/OrthoFinder/files/1998496/Species0.txt)

However, I'm not sure why the previous version of blast behaves this way. Any thoughts?
